# Generated by Django 4.1.5 on 2023-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_decisionmaker_application_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(default='None', max_length=11),
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='applicant',
            name='postalcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='siblings',
            field=models.IntegerField(default=0),
        ),
    ]
