# Generated by Django 4.1.5 on 2023-01-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_applicant_address_applicant_city_applicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=500),
        ),
    ]
