# Generated by Django 4.1.5 on 2023-01-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Roll',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cnic',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
