# Generated by Django 4.1.5 on 2023-01-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_applicant_roll_alter_applicant_cnic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.AddField(
            model_name='application',
            name='Roll',
            field=models.CharField(default='XXF-XXXX', max_length=8),
        ),
    ]
