# Generated by Django 4.1.5 on 2023-01-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_applicant_user_remove_application_applicant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
