# Generated by Django 4.1.5 on 2023-03-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='UtilityBill',
        ),
        migrations.AddField(
            model_name='applicant',
            name='altphone',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cpga',
            field=models.FloatField(default=0.0, max_length=4),
        ),
        migrations.AddField(
            model_name='applicant',
            name='profilephoto',
            field=models.ImageField(default='profilephoto/default.jpg', upload_to='profilephoto'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='assets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ebilldoc',
            field=models.FileField(default='ebilldoc/default.pdf', upload_to='ebilldoc'),
        ),
        migrations.AddField(
            model_name='application',
            name='electricityBill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='gasBill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='gbilldoc',
            field=models.FileField(default='gbilldoc/default.pdf', upload_to='gbilldoc'),
        ),
        migrations.AddField(
            model_name='application',
            name='propertystatus',
            field=models.BooleanField(default=False, help_text="True if property is owned by the applicant's family, False if property is rented by the applicant's family.", verbose_name='Property Status'),
        ),
        migrations.AddField(
            model_name='application',
            name='siblingsEdufee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='transcript',
            field=models.FileField(default='transcript/default.pdf', upload_to='transcript'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
