# Generated by Django 4.1.5 on 2023-03-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_application_utilitybill_applicant_altphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicationstatus',
            field=models.IntegerField(default=0),
        ),
    ]
