# Generated by Django 4.1.5 on 2023-03-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_applicant_user_alter_application_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applicationstatus',
            field=models.IntegerField(default=0),
        ),
    ]
