# Generated by Django 4.2.1 on 2023-05-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_application_aidamount_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('aidamount', models.CharField(max_length=30)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.application')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
