# Generated by Django 4.2.1 on 2023-05-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_user_email_alter_user_name_returnloan'),
        ('base', '0016_alter_facultyvotes_user'),
    ]

    operations = [
    ]
