# Generated by Django 4.2.1 on 2023-05-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_merge_20230516_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
