# Generated by Django 4.2.1 on 2023-05-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_user_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='cpga',
            new_name='cgpa',
        ),
        migrations.AddField(
            model_name='application',
            name='predicted_aid',
            field=models.IntegerField(default=0),
        ),
    ]
