# Generated by Django 3.2.8 on 2023-05-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_application_propertystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='profilephoto',
            field=models.ImageField(default='profilephoto/default.jpg', upload_to='profilephoto/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ebilldoc',
            field=models.FileField(default='ebilldoc/default.pdf', upload_to='ebilldoc/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gbilldoc',
            field=models.FileField(default='gbilldoc/default.pdf', upload_to='gbilldoc/'),
        ),
    ]
